/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/motor.glb 
Author: XploRXR (https://sketchfab.com/XploRXR)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/electric-motor-2204cb42b16b4ea1bff777d948b7c12f
Title: Electric Motor
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/motor.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh geometry={nodes.Coils_Coil_MAT001_0.geometry} material={materials['Coil_MAT.001']} scale={100} />
        <mesh geometry={nodes.Cores_Iron_MAT001_0.geometry} material={materials['Iron_MAT.001']} scale={100} />
        <mesh geometry={nodes.Hub_BlackPlast_MAT001_0.geometry} material={materials['BlackPlast_MAT.001']} scale={100} />
        <mesh geometry={nodes.Rotor_Iron_MAT001_0.geometry} material={materials['Iron_MAT.001']} scale={100} />
        <mesh geometry={nodes.Spools_BlackPlast_MAT001_0.geometry} material={materials['BlackPlast_MAT.001']} scale={100} />
      </group>
    </group>
  )
}

useGLTF.preload('/motor.glb')
